<ips:template parameters="$categories" />

<div class="ipsBox ipsPad_half" data-role="categoryList">
    <div class="ipsSideMenu ipsSideMenu_withRadios ipsType_medium" id="merchCategories">
        <ul class="ipsSideMenu_list">
            {{foreach $categories as $category}}
                <li>
                    <a href='{$category->url()}' class="ipsSideMenu_item{{if \IPS\Request::i()->category == $category->id}} ipsSideMenu_itemActive{{endif}}">
                        <strong>{$category->_title}</strong>
                    </a>
                    {{if $children = $category->children('view', NULL, FALSE)}}
                        {template="menuChildren" app="printfulintegration" group="store" location="front" params="$children"}
                    {{endif}}
                </li>
            {{endforeach}}
        </ul>
    </div>
</div>